FROM python:3.9-slim-buster

RUN mkdir /vk_bot

COPY . /vk_bot/

WORKDIR /vk_bot

RUN python -m pip install -r /vk_bot/requirements.txt

#RUN python insert_test_data.py

ENTRYPOINT ["python", "main.py"]
